-- Built-in exercise library (created_by_user_id = NULL marks an exercise as built-in).
-- Users can log/route these but not edit or delete them.

INSERT INTO exercise (id, name, exercise_type, equipment, primary_muscle_group, image_url, created_by_user_id) VALUES
-- Chest
(UUID_TO_BIN(UUID()), 'Bench Press (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bench Press (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Incline Bench Press (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Incline Bench Press (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Decline Bench Press (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Chest Press (Machine)', 'WEIGHT_REPS', 'MACHINE', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Chest Fly (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Chest Fly (Cable)', 'WEIGHT_REPS', 'CABLE', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Chest Fly (Machine)', 'WEIGHT_REPS', 'MACHINE', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Cable Crossover', 'WEIGHT_REPS', 'CABLE', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Push Up', 'BODYWEIGHT', 'BODYWEIGHT', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Push Up (Weighted)', 'WEIGHTED_BODYWEIGHT', 'BODYWEIGHT', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Archer Push Up', 'BODYWEIGHT', 'BODYWEIGHT', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Dip (Chest)', 'BODYWEIGHT', 'BODYWEIGHT', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Dip (Weighted)', 'WEIGHTED_BODYWEIGHT', 'BODYWEIGHT', 'CHEST', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Dip (Assisted)', 'ASSISTED_BODYWEIGHT', 'MACHINE', 'CHEST', NULL, NULL),

-- Back / Lats / Upper back
(UUID_TO_BIN(UUID()), 'Deadlift (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'LOWER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Romanian Deadlift (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'HAMSTRINGS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Romanian Deadlift (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'HAMSTRINGS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Pull Up', 'BODYWEIGHT', 'BODYWEIGHT', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Pull Up (Weighted)', 'WEIGHTED_BODYWEIGHT', 'BODYWEIGHT', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Pull Up (Assisted)', 'ASSISTED_BODYWEIGHT', 'MACHINE', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Negative Pull Up', 'BODYWEIGHT', 'BODYWEIGHT', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Chin Up', 'BODYWEIGHT', 'BODYWEIGHT', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Chin Up (Weighted)', 'WEIGHTED_BODYWEIGHT', 'BODYWEIGHT', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Lat Pulldown (Cable)', 'WEIGHT_REPS', 'CABLE', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Lat Pulldown (Machine)', 'WEIGHT_REPS', 'MACHINE', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bent Over Row (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bent Over Row (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Seated Cable Row', 'WEIGHT_REPS', 'CABLE', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'T-Bar Row', 'WEIGHT_REPS', 'BARBELL', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Row (Machine)', 'WEIGHT_REPS', 'MACHINE', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Inverted Row', 'BODYWEIGHT', 'BODYWEIGHT', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Australian Pull Up', 'BODYWEIGHT', 'BODYWEIGHT', 'UPPER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Muscle Up', 'BODYWEIGHT', 'BODYWEIGHT', 'LATS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Back Extension', 'BODYWEIGHT', 'BODYWEIGHT', 'LOWER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Good Morning (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'LOWER_BACK', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Shrug (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'TRAPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Shrug (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'TRAPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Face Pull (Cable)', 'WEIGHT_REPS', 'CABLE', 'UPPER_BACK', NULL, NULL),

-- Shoulders
(UUID_TO_BIN(UUID()), 'Overhead Press (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Overhead Press (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Shoulder Press (Machine)', 'WEIGHT_REPS', 'MACHINE', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Arnold Press (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Lateral Raise (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Lateral Raise (Cable)', 'WEIGHT_REPS', 'CABLE', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Front Raise (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Rear Delt Fly (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Rear Delt Fly (Machine)', 'WEIGHT_REPS', 'MACHINE', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Upright Row (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Pike Push Up', 'BODYWEIGHT', 'BODYWEIGHT', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Handstand Push Up', 'BODYWEIGHT', 'BODYWEIGHT', 'SHOULDERS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Wall Handstand Hold', 'DURATION', 'BODYWEIGHT', 'SHOULDERS', NULL, NULL),

-- Biceps
(UUID_TO_BIN(UUID()), 'Bicep Curl (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'BICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bicep Curl (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'BICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bicep Curl (Cable)', 'WEIGHT_REPS', 'CABLE', 'BICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Hammer Curl (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'BICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Preacher Curl (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'BICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Concentration Curl', 'WEIGHT_REPS', 'DUMBBELL', 'BICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'EZ Bar Curl', 'WEIGHT_REPS', 'BARBELL', 'BICEPS', NULL, NULL),

-- Triceps
(UUID_TO_BIN(UUID()), 'Triceps Pushdown (Cable)', 'WEIGHT_REPS', 'CABLE', 'TRICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Triceps Extension (Overhead)', 'WEIGHT_REPS', 'DUMBBELL', 'TRICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Skull Crusher (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'TRICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Close Grip Bench Press', 'WEIGHT_REPS', 'BARBELL', 'TRICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Dip (Triceps)', 'BODYWEIGHT', 'BODYWEIGHT', 'TRICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bench Dip', 'BODYWEIGHT', 'BODYWEIGHT', 'TRICEPS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Diamond Push Up', 'BODYWEIGHT', 'BODYWEIGHT', 'TRICEPS', NULL, NULL),

-- Forearms
(UUID_TO_BIN(UUID()), 'Wrist Curl (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'FOREARMS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Farmer''s Walk', 'WEIGHT_DURATION', 'DUMBBELL', 'FOREARMS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Dead Hang', 'DURATION', 'BODYWEIGHT', 'FOREARMS', NULL, NULL),

-- Quads / Glutes
(UUID_TO_BIN(UUID()), 'Squat (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Front Squat (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Goblet Squat (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Squat (Bodyweight)', 'BODYWEIGHT', 'BODYWEIGHT', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Pistol Squat', 'BODYWEIGHT', 'BODYWEIGHT', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Leg Press (Machine)', 'WEIGHT_REPS', 'MACHINE', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Leg Extension (Machine)', 'WEIGHT_REPS', 'MACHINE', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Lunge (Dumbbell)', 'WEIGHT_REPS', 'DUMBBELL', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Lunge (Bodyweight)', 'BODYWEIGHT', 'BODYWEIGHT', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Walking Lunge', 'WEIGHT_REPS', 'DUMBBELL', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Bulgarian Split Squat', 'WEIGHT_REPS', 'DUMBBELL', 'QUADS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Hip Thrust (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'GLUTES', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Glute Bridge', 'BODYWEIGHT', 'BODYWEIGHT', 'GLUTES', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Hip Abduction (Machine)', 'WEIGHT_REPS', 'MACHINE', 'GLUTES', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Cable Kickback', 'WEIGHT_REPS', 'CABLE', 'GLUTES', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Step Up', 'WEIGHT_REPS', 'DUMBBELL', 'QUADS', NULL, NULL),

-- Hamstrings / Calves
(UUID_TO_BIN(UUID()), 'Leg Curl (Machine)', 'WEIGHT_REPS', 'MACHINE', 'HAMSTRINGS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Nordic Hamstring Curl', 'BODYWEIGHT', 'BODYWEIGHT', 'HAMSTRINGS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Stiff Leg Deadlift', 'WEIGHT_REPS', 'BARBELL', 'HAMSTRINGS', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Calf Raise (Standing)', 'WEIGHT_REPS', 'MACHINE', 'CALVES', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Calf Raise (Seated)', 'WEIGHT_REPS', 'MACHINE', 'CALVES', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Calf Raise (Bodyweight)', 'BODYWEIGHT', 'BODYWEIGHT', 'CALVES', NULL, NULL),

-- Core
(UUID_TO_BIN(UUID()), 'Plank', 'DURATION', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Side Plank', 'DURATION', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Crunch', 'BODYWEIGHT', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Cable Crunch', 'WEIGHT_REPS', 'CABLE', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Sit Up', 'BODYWEIGHT', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Hanging Leg Raise', 'BODYWEIGHT', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Hanging Knee Raise', 'BODYWEIGHT', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Toes to Bar', 'BODYWEIGHT', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'L-Sit Hold', 'DURATION', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Russian Twist', 'WEIGHT_REPS', 'PLATE', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Ab Wheel Rollout', 'BODYWEIGHT', 'OTHER', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Mountain Climber', 'REPS_ONLY', 'BODYWEIGHT', 'CORE', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Dragon Flag', 'BODYWEIGHT', 'BODYWEIGHT', 'CORE', NULL, NULL),

-- Full body / Kettlebell
(UUID_TO_BIN(UUID()), 'Kettlebell Swing', 'WEIGHT_REPS', 'KETTLEBELL', 'FULL_BODY', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Clean and Jerk (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'FULL_BODY', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Snatch (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'FULL_BODY', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Thruster (Barbell)', 'WEIGHT_REPS', 'BARBELL', 'FULL_BODY', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Turkish Get Up', 'WEIGHT_REPS', 'KETTLEBELL', 'FULL_BODY', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Burpee', 'REPS_ONLY', 'BODYWEIGHT', 'FULL_BODY', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Battle Ropes', 'DURATION', 'OTHER', 'FULL_BODY', NULL, NULL),

-- Cardio
(UUID_TO_BIN(UUID()), 'Running', 'DISTANCE', 'OTHER', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Treadmill Run', 'DISTANCE', 'MACHINE', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Cycling', 'DISTANCE', 'MACHINE', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Rowing (Machine)', 'DISTANCE', 'MACHINE', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Stair Climber', 'DURATION', 'MACHINE', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Elliptical', 'DURATION', 'MACHINE', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Jump Rope', 'DURATION', 'OTHER', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Swimming', 'DISTANCE', 'OTHER', 'CARDIO', NULL, NULL),
(UUID_TO_BIN(UUID()), 'Walking', 'DISTANCE', 'OTHER', 'CARDIO', NULL, NULL);
